services:
    web-server:
        build:
            dockerfile: ./.docker/src/httpd/Dockerfile
            args:
                - SERVER_NAME=${SERVER_NAME}
                - USE_SSL=${USE_SSL:-false}
        ports:
            - "${FORWARD_SERVER_PORT:-8000}:80"
            - "${FORWARD_SERVER_PORT_SSL:-8443}:443"
        volumes:
            - ./.docker/mount-exclude/directory:/var/www/html/.docker:ro
            - ./.docker/mount-exclude/file:/var/www/html/docker-compose.yml:ro
            - ./:/var/www/html
    application:
        environment:
            MAILPIT_HOST: "mail"
            MAILPIT_PORT: "1025"
            MYSQL_HOST: "database"
            MYSQL_PORT: "3306"
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            REDIS_HOST: "cache"
            REDIS_PORT: "6379"
        build:
            dockerfile: ./.docker/src/php-fpm/Dockerfile
            target: base
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        ports:
            - "${FORWARD_VITE_PORT:-5173}:${FORWARD_VITE_PORT:-5173}"
        volumes:
            - ./.docker/src/php-fpm/conf/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
            - ./.docker/src/php-fpm/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
            - ./.docker/mount-exclude/directory:/var/www/html/.docker:ro
            - ./.docker/mount-exclude/file:/var/www/html/docker-compose.yml:ro
            - ./:/var/www/html
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - web-server
    mail:
        image: axllent/mailpit:latest
        ports:
            - "${FORWARD_MAILPIT_UI_PORT:-8025}:8025"
            - "${FORWARD_MAILPIT_SMTP_PORT:-1025}:1025"
        volumes:
            - mailpitdata:/data
    database:
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        image: mysql:8.4
        ports:
            - "${FORWARD_MYSQL_PORT:-3306}:3306"
        volumes:
            - mysqldata:/var/lib/mysql
        command: [ "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci" ]
    cache:
        image: redis:7.4-alpine
        ports:
            - "${FORWARD_REDIS_PORT:-6379}:6379"
        volumes:
            - redisdata:/data
    adminer:
        environment:
            ADMINER_DEFAULT_SERVER: "database:3306"
            ADMINER_DEFAULT_DRIVER: "server"
            ADMINER_DEFAULT_USER: ${MYSQL_USER}
            ADMINER_DEFAULT_DATABASE: ${MYSQL_DATABASE}
            ADMINER_DEFAULT_PASSWORD: ${MYSQL_PASSWORD}
            ADMINER_PLUGINS: ${ADMINER_PLUGINS:-dark-switcher prism table-indexes-structure table-structure}
        image: adminer:latest
        ports:
            - "${FORWARD_ADMINER_PORT:-8080}:8080"
        volumes:
            - ./.docker/src/adminer/login-default-credentials.php:/var/www/html/plugins-enabled/login-default-credentials.php

volumes:
    mailpitdata:
    mysqldata:
    redisdata:
